name: Push
on:
  push:
    branches:
     - main
    paths:
      - '*'
defaults:
  run:
    working-directory: .          
jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Black
        run: pip install black

      - name: Run Black
        uses: psf/black@stable
        with:
          src: "."

      - name: Install flake8
        run: pip install flake8

      - uses: TrueBrain/actions-flake8@v2

      - name: Install Pulumi
        run: |
          python3 -m venv venv
          venv/bin/pip install -r requirements.txt

      - name: Run pulumi up
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: org
          work-dir: "."          
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
