name: Push
on:
  push:
    branches:
     - main
jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Pulumi
        run: |
          python3 -m venv venv
          venv/bin/pip install -r requirements.txt

      - name: Run pulumi up
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: org
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
